Sales of products in four different regions is tabulated for males and females.
Find if male-female buyer rations are similar across regions.

Hypothesis

Null Hypothesis (H0) - Both Male and Female buyer ratios are similar across regions
Alternative Hypothesis (H1) - Buyer ratios are not similar across regions

In [3]:
import numpy as np
import pandas as pd
from scipy import stats as stats

In [4]:
data = pd.read_csv("C:\\Users\\ARPITHA S\\Desktop\\Data Science\\Data Sets\\BuyerRatio.csv")
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [5]:
#Removing 1st column
data = data.iloc[:, 1:6]
data

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [6]:
data.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [7]:
val=stats.chi2_contingency(data)
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [8]:
type(val)

tuple

In [9]:
no_of_rows=len(data.iloc[:,0])   # Number of rows = 2
no_of_columns=len(data.iloc[0,:])    # Number of columns = 4
degree_of_freedom=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_freedom)

Degree of Freedom= 3


In [10]:
Expected_value = val[degree_of_freedom]
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [11]:
#Importing Chi-Square
from scipy.stats import chi2

In [12]:
chi_square=sum([(o-e)**2/e for o,e in zip(data.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

1.5152956451130446

In [13]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [14]:
if chi_square_statestic >= critical_value:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')   #Accepting the Null Hypothesis(H0)

Independent (fail to reject H0)


In [15]:
pvalue=1-chi2.cdf(chi_square_statestic,3)
pvalue

0.6787446296467897

In [ ]:
#Comaring the p-value i.e 0.67 with 0.05
if pvalue <= 0.05:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')  #Accepting the Null Hypothesis(H0)

Conclusion

Since the chi2 is failed to rejecting the Null Hypothesis(H0), which means it is accepting the H0.
Therefore the male and female buyer rations are similar across regions